# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 09:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_path', models.FilePathField(blank=True, null=True, path='myblog/static/myblog/articleimgs/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('is_original', models.BooleanField(default=False)),
                ('eyes_count', models.IntegerField(default=0)),
                ('summary', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BlogDateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blogcategory',
            field=models.ManyToManyField(to='myblog.BlogCategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogdatecategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.BlogDateCategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.BlogType'),
        ),
    ]
