# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_path',
            field=models.FilePathField(blank=True, null=True, path='myblog/articleimgs/'),
        ),
    ]
