# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20170422_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
