# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20170422_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
